services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://n8n:5678/
      - GENERIC_TIMEZONE=Africa/Lagos
    volumes:
      - n8n_data:/home/node/.n8n
    user: "1000:1000"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: n8n_postgres
    restart: always
    environment:
      POSTGRES_DB: n8n_automation_table
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nodeapp:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: n8n_automation_table
      DB_USER: postgres
      DB_PASSWORD: Admin
      PORT: 3000

      # ðŸ‘‡ Replace `/webhook/your-workflow-path` with the actual n8n webhook path
      N8N_WEBHOOK_URL: http://n8n:5678/webhook-test/wallet-email
    depends_on:
      - postgres
      - n8n

    # â›” Removed `npm run setup-db` from here â€“ only run it manually when needed
    command: sh -c "sleep 10 && npm start"

volumes:
  n8n_data:
  pg_data:
